### ISSUE TITLE
Relative @imports don't work

### ISSUE THREAD

**Issue by simonomis** [Aaike/jspm-less-plugin#1]
The less compiler doesn't know the path for the less file because it just gets the contents of the file.

If you add the filename option to the call `less.render()`, it can work out where to base relative imports from. If you change line 26 of less.js to:

    less.render(data, { filename: url }).then(function(data){
      ...
    });

That should do it I think.

**Comment by Aaike** [comment]
Could you test this to confirm and submit a PR ? i will accept it if you have tested it.

If not i will try to get it to work in the coming few days if i find some time ;)

**Comment by simonomis** [comment]
Sure, I'll try to put together a PR tomorrow
